apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-fgmn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-fgmn
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-fgmn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-fgmn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-fgmn
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-hrug-tenant/dotnet-component/devfile-sample-dotnet60-basic-fgmn@sha256:08192248eac2c2405fed009f1bc986dffc9415820d4662afa21c37129d53f7a8
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
